version: "3"

services:
  java:
    image: 301151589520.dkr.ecr.ap-northeast-1.amazonaws.com/java
    ports:
      - 8080:8080
    working_dir: /api

  react:
    image: 301151589520.dkr.ecr.ap-northeast-1.amazonaws.com/react
    ports:
      - "3000:3000"
    working_dir: /front

  mysql:
    image: 301151589520.dkr.ecr.ap-northeast-1.amazonaws.com/mysql
    container_name: winter-mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: winter
      MYSQL_USER: winter
      MYSQL_PASSWORD: password

  redis:
    image: redis:latest
    container_name: winter-redis
    ports:
      - "6379"
    command: redis-server --requirepass password --appendonly yes
